### PR TITLE
Issue/240

### PR DESCRIPTION
**Pull request by pvawser01**
Removed i18n active record backend from Koi. The application rb generator has also had this removed so new projects won't use it.

### CODE REVIEW

**Comment by Obversity** [comment]
I tested the bootstrap process and I'm getting a stack level too deep issues on some commands, but I'm getting this problem in master as well, so it's this branch that introduced the problem. 

Worth looking into separately, just commenting here since I noticed it while testing this.

**Comment by pvawser01** [comment]
> I'm getting this problem in master as well, so it's this branch that introduced the problem.

Do you mean "it's not this branch" 😄

**Comment by Obversity** [comment]
@pvawser01 Ugh, yup! That's exactly what I mean. My bad.

**Comment by Obversity** [comment]
Turns out the stack level too deep issue was from me trying to run the generator without setting the ruby version first (i.e. the rbenv was set to use 2.4, where koi currently uses 2.2.2).

**Comment by Obversity** [comment]
@pvawser01  Would be good to get this merged. Any news on why it caused so many Gemfile.lock changes? I'm worried that some of those version bumps might break stuff without thorough testing.

**Comment by pvawser01** [comment]
@Obversity Pretty sure this was due to bundling the dummy app. It must have had a koi version upgrade at some point so When I built it locally, it would get the latest versions of things.

**Comment by Obversity** [comment]
@pvawser01 Sounds about right. Do we want those changes in master?

**Comment by pvawser01** [comment]
@Obversity Can't see why not. It looks like it's only for the demo app. But if you feel more comfortable not including the gem lock changes, we can roll it back.

**Comment by Obversity** [comment]
It looks like it's the Gemfile.lock in the root directory of the project. In either case, as long as it's tested and runs okay, I don't suppose it's a problem. (We'll need to do a pretty thorough test of Koi before we release the last 2.x version.)

It'll all change in Koi 3 anyway!

**Pull request closed without merging**
