### PR TITLE
Fix: Console errors on loading pages with select2

### PR DESCRIPTION
**Pull request by SughoshRao**
Checks if arrays are defined before performing functions on them

Select2 (multiselect) fields are currently broken on latest Koi v2.4.6. I've made a probably controversial decision to copy select2.js into Koi vendor/javascripts to fix this error.. would like some advice on how to proceed if this PR is not acceptable

### CODE REVIEW

**Comment by sobakasu** [comment]
had a brief look, I see we use select2-rails gem in Koi which is supposed to let us use `//= require select2`, which we are doing in admin.js, and the koi manifest config/koi.js includes admin.js.
will need to investigate why this doesn't work. does the project you're testing on include the koi.js manifest?

**Comment by SughoshRao** [comment]
I've made the below change in the select2.js file: I've added a check to see if `instance[options]` is defined before doing the `.apply()` on the array

This check is not there in the select2.js from the `select2-rails` gem.

```
if (instance[options]) {
  ret = instance[options].apply(instance, args);
}
```

**Comment by SughoshRao** [comment]
I think this is actually a bug in select2-rails.. will make a PR there and see how we go

**Comment by sfnelson** [comment]
@SughoshRao why do you need to include select2 when your change is in koi?

**Comment by SughoshRao** [comment]
@sfnelson I've made a change to the select.js file that's mentioned above..

**Comment by SughoshRao** [comment]
Spoke with Stephen on this. Closing this PR as the bug is in our Koi code, not the library itself. Will investigate and make a new PR

**Pull request closed without merging**
